### ISSUE TITLE
Installed modes are missing files


### ISSUE THREAD

**Issue by nlhowell** [apertium/apertium-tel#1]
modes.xml includes some modes with `install="yes"`, but the required
files aren't installed.

Some generic suggestions:
* -lexc and -twol modes probably aren't useful to users
* -spell modes should depend on --enable-ospell
* .deps files are never installed, so any modes using them shouldn't be
  installed.

* Messages for package app-dicts/apertium-tel-9999:

* Failed to find '/usr/share/apertium/apertium-tel/.deps/tel.twol.hfst' in install image.
* QA: missing files required for mode tel-twol.
* Failed to find '/usr/share/apertium/apertium-tel/.deps/tel.LR.lexc.hfst' in install image.
* QA: missing files required for mode tel-lexc.

**Comment by mr-martian** [comment]
fixed in 5281e6aa618906a26c54a2670b10e5c54d991ddd
